{{ config(materialized='view') }}

Select distinct COURSE_MNEMONIC ,COURSE_NAME from ERD_UVA_COURSES INNER JOIN 
DS5111_DB.LAB01_BCB2GS.ERD_UVA_ASSIGNMENTS ON 
ERD_UVA_COURSES.COURSE_ID = ERD_UVA_ASSIGNMENTS.COURSE_ID 
AND ACTIVE_FLAG <> 'TRUE'
